randu=function(x0,n)
{
x=rep(0,n+1)
x[1]=x0
for(i in 1:n+1)
{
if(i==1)
x[i]=x0
else
x[i]=(65539*x[i-1])%%(2^31)
}
return(x[-1])
}
n = 3000
r = randu(314159, n) #get n random numbers from RANDU
#show triplets from RANDU lie on 1 of 15 planes
t = matrix(r/(2^31), ncol = 3, byrow = T)
t = as.data.frame(t)
plot(t[,1], 9*t[,1]-6*t[,2]+t[,3], pch = 16, col = "red", xlab = "X_k",
     ylab = "(9X_k - 6X_(k+1) + X_(k+2))/2^31", main = "Plot of 1000 triplets generated by RANDU")
